name: scp files
on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  symfony:
    name: Deploy to production
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: ssh key with passphrase
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH2 }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        source: "tests/a.txt,tests/b.txt"
        target: "test"